config/routes.rb
Rails.application.routes.draw do
  root 'sub_reddits#index'
  resources :related_sub_reddits
  resources :sub_reddits

end

app/models/related_sub_reddit.rb
class RelatedSubReddit < ActiveRecord::Base
  belongs_to :sub_reddit
  belongs_to :sub_reddit_relation, class_name: 'SubReddit'

  def to_s
    "#{sub_reddit.name} #{sub_reddit_relation.name}" if sub_reddit && sub_reddit_relation
  end

  def self.all_relations(sub_reddit)
    (self.where(:sub_reddit_id => sub_reddit.id).map(&:sub_reddit_relation) +
    self.where(:sub_reddit_relation => sub_reddit.id).map(&:sub_reddit)).uniq
  end
end

app/models/sub_reddit.rb
class SubReddit < ActiveRecord::Base
  has_many :related_sub_reddits, dependent: :destroy
  belongs_to :sub_reddit_report
  serialize :bag_of_words

  def to_s
    name
  end

  def all_related_subreddit_relations
    (RelatedSubReddit.where(:sub_reddit_relation => self.id) + RelatedSubReddit.where(:sub_reddit => self.id)).sort_by(&:weight)
  end
end

app/models/sub_reddit_report.rb
class SubRedditReport < ActiveRecord::Base
  has_many :sub_reddits, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/related_sub_reddits_controller.rb
class RelatedSubRedditsController < ApplicationController
  before_action :set_related_sub_reddit, only: [:show, :edit, :update, :destroy]

  # GET /related_sub_reddits
  # GET /related_sub_reddits.json
  def index
    @related_sub_reddits = RelatedSubReddit.limit(20).all
  end

  # GET /related_sub_reddits/1
  # GET /related_sub_reddits/1.json
  def show
  end

  # GET /related_sub_reddits/new
  def new
    @related_sub_reddit = RelatedSubReddit.new
  end

  # GET /related_sub_reddits/1/edit
  def edit
  end

  # POST /related_sub_reddits
  # POST /related_sub_reddits.json
  def create
    @related_sub_reddit = RelatedSubReddit.new(related_sub_reddit_params)

    respond_to do |format|
      if @related_sub_reddit.save
        format.html { redirect_to @related_sub_reddit, notice: 'Related sub reddit was successfully created.' }
        format.json { render :show, status: :created, location: @related_sub_reddit }
      else
        format.html { render :new }
        format.json { render json: @related_sub_reddit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /related_sub_reddits/1
  # PATCH/PUT /related_sub_reddits/1.json
  def update
    respond_to do |format|
      if @related_sub_reddit.update(related_sub_reddit_params)
        format.html { redirect_to @related_sub_reddit, notice: 'Related sub reddit was successfully updated.' }
        format.json { render :show, status: :ok, location: @related_sub_reddit }
      else
        format.html { render :edit }
        format.json { render json: @related_sub_reddit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /related_sub_reddits/1
  # DELETE /related_sub_reddits/1.json
  def destroy
    @related_sub_reddit.destroy
    respond_to do |format|
      format.html { redirect_to related_sub_reddits_url, notice: 'Related sub reddit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_related_sub_reddit
    @related_sub_reddit = RelatedSubReddit.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def related_sub_reddit_params
    params.require(:related_sub_reddit).permit(:sub_reddit_id, :weight, :sub_reddit_relation_id)
  end
end

app/controllers/sub_reddits_controller.rb
class SubRedditsController < ApplicationController
  before_action :set_sub_reddit, only: [:show, :edit, :update, :destroy]
  before_action :set_top_10_related_sub_reddits, only: [:index]

  # GET /sub_reddits
  # GET /sub_reddits.json
  def index
    @sub_reddits = SubReddit.all
  end

  # GET /sub_reddits/1
  # GET /sub_reddits/1.json
  def show
  end

  # GET /sub_reddits/new
  def new
    @sub_reddit = SubReddit.new
  end

  # GET /sub_reddits/1/edit
  def edit
  end

  # POST /sub_reddits
  # POST /sub_reddits.json
  def create
    @sub_reddit = SubReddit.create(sub_reddit_params)

    context = CreateSubreddit.call(sub_reddit: @sub_reddit)

    respond_to do |format|
      if context.succuss?

        format.html { redirect_to sub_reddits, notice: 'Sub reddit was successfully created.' }
        format.json { render :show, status: :created, location: @sub_reddit }
      else
        puts 'here'
        format.html { render :new }
        format.json { render json: @sub_reddit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_reddits/1
  # PATCH/PUT /sub_reddits/1.json
  def update
    respond_to do |format|
      if @sub_reddit.update(sub_reddit_params)
        format.html { redirect_to @sub_reddit, notice: 'Sub reddit was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_reddit }
      else
        format.html { render :edit }
        format.json { render json: @sub_reddit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_reddits/1
  # DELETE /sub_reddits/1.json
  def destroy
    @sub_reddit.destroy
    respond_to do |format|
      format.html { redirect_to sub_reddits_url, notice: 'Sub reddit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_sub_reddit
    @sub_reddit = SubReddit.find(params[:id])
  end

  # Get 20 relations on subreddits and remove every other one.
  def set_top_10_related_sub_reddits
    @top_10_related_sub_reddits = RelatedSubReddit
                                  .order(weight: :desc)
                                  .limit(20)
                                  .all
                                  .to_a
                                  .each_slice(2).map(&:last)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def sub_reddit_params
    params.require(:sub_reddit).permit(:name, :url, :document, :bag_of_words)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SubredditRelations</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<script type="text/javascript">
  $('.progress .progress-bar').progressbar();
  $(document).ready(function() {
      $('.progress .progress-bar').progressbar();
  });
</script>

<%= yield %>

</body>
</html>

app/views/related_sub_reddits/_form.html.erb
<%= form_for(@related_sub_reddit) do |f| %>
  <% if @related_sub_reddit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@related_sub_reddit.errors.count, "error") %> prohibited this related_sub_reddit from being saved:</h2>

      <ul>
      <% @related_sub_reddit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sub_reddit_id %><br>
    <%= f.text_field :sub_reddit_id %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :sub_reddit_relation_id %><br>
    <%= f.text_field :sub_reddit_relation_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/related_sub_reddits/edit.html.erb
<h1>Editing Related Sub Reddit</h1>

<%= render 'form' %>

<%= link_to 'Show', @related_sub_reddit %> |
<%= link_to 'Back', related_sub_reddits_path %>

app/views/related_sub_reddits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Related Sub Reddits</h1>

<table class ='table table-striped'>
  <thead>
    <tr>
      <th>Sub reddit</th>
      <th>Weight</th>
      <th>Sub reddit relation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @related_sub_reddits.each do |related_sub_reddit| %>
      <tr>
        <td><%= related_sub_reddit.sub_reddit.name %></td>
        <td><%= related_sub_reddit.weight %></td>
        <td><%= related_sub_reddit.sub_reddit_relation.name %></td>
        <td><%= link_to 'Show', related_sub_reddit %></td>
        <td><%= link_to 'Edit', edit_related_sub_reddit_path(related_sub_reddit) %></td>
        <td><%= link_to 'Destroy', related_sub_reddit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Related sub reddit', new_related_sub_reddit_path %>

app/views/related_sub_reddits/new.html.erb
<h1>New Related Sub Reddit</h1>

<%= render 'form' %>

<%= link_to 'Back', related_sub_reddits_path %>

app/views/related_sub_reddits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sub reddit:</strong>
  <%= @related_sub_reddit.sub_reddit %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @related_sub_reddit.weight %>
</p>

<p>
  <strong>Sub reddit relation:</strong>
  <%= @related_sub_reddit.sub_reddit_relation %>
</p>

<%= link_to 'Edit', edit_related_sub_reddit_path(@related_sub_reddit) %> |
<%= link_to 'Back', related_sub_reddits_path %>

app/views/sub_reddits/_form.html.erb
<%= form_for(@sub_reddit) do |f| %>
  <% if @sub_reddit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sub_reddit.errors.count, "error") %> prohibited this sub_reddit from being saved:</h2>

      <ul>
      <% @sub_reddit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :document %><br>
    <%= f.text_field :document, :cols => "10", :rows => "10", :readonly => true %>
  </div>
  <div class="field">
    <%= f.label :bag_of_words %><br>
    <%= f.text_field :bag_of_words, :cols => "10", :rows => "10", :readonly => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sub_reddits/edit.html.erb
<h1>Editing Sub Reddit</h1>

<%= render 'form' %>

<%= link_to 'Show', @sub_reddit %> |
<%= link_to 'Back', sub_reddits_path %>

app/views/sub_reddits/index.html.erb
<p id="notice"><%= notice %></p>

<div id="log"></div>
</div>
<br>
<!-- <h1>Listing Sub Reddits</h1>
<table class ='table table-striped'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @sub_reddits.each do |sub_reddit| %>
      <tr>
        <td><%= link_to sub_reddit.name, sub_reddit  %></td>
        <td><%= sub_reddit.url %></td>
        <td><%= link_to 'Edit', edit_sub_reddit_path(sub_reddit), :class => 'btn btn-default' %>
        <%= link_to 'Destroy', sub_reddit, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table> -->

<h4>Top 10 highest weighted relations</h4>
<table class ='table table-striped'>
  <thead>
    <tr>
      <th>Sub reddit</th>
      <th>Weight</th>
      <th>Sub reddit relation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @top_10_related_sub_reddits.each do |related_sub_reddit| %>
      <tr>
        <td><%= link_to related_sub_reddit.sub_reddit.name, related_sub_reddit.sub_reddit  %></td>
        <td><div class="progress">
            <div class="progress-bar" role="progressbar" data-transitiongoal="<%= related_sub_reddit.weight*100 %>"></div>
            </div>
        </td>
        <td><%= link_to related_sub_reddit.sub_reddit_relation.name, related_sub_reddit.sub_reddit_relation  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub reddit', new_sub_reddit_path %>

app/views/sub_reddits/new.html.erb
<!-- <h1>New Sub Reddit</h1> -->

<%= render 'form' %>

<%= link_to 'Back', sub_reddits_path %>

app/views/sub_reddits/show.html.erb
<div class="container-fluid">
  <p id="notice"><%= notice %></p>

  <h2 class="page-header text-primary">
    <strong>Subreddit Name:</strong>
    <%= @sub_reddit.name %>
  </h2>

  <p>
    <strong>Url:</strong>
    <%= @sub_reddit.url %>
  </p>

  <p>
    <strong>Latest Snapshot:</strong>
    <%= @sub_reddit.updated_at %>
  </p>

  <p>
    <strong>Document:</strong>
    <%= @sub_reddit.document %>
  </p>

  <p>
    <strong>Bag of words:</strong>
    <%= @sub_reddit.bag_of_words %>
  </p>


  <!-- <strong>Word Cloud:</strong>
  <div id="example" style="width: 700px; height: 350px"></div> -->

  <table class='table table-striped table-hover'>
    <thead>
      <tr>
        <th><!-- class='sub-reddit'--><strong>Suggested Subreddits</strong></th>
        <th class='sub-reddit'><strong>Relevance</strong></th>
        <th colspan="2">&nbsp;</th>
      </tr>
    </thead>

    <% if @sub_reddit.all_related_subreddit_relations.first && @sub_reddit.related_sub_reddits.count > 0 %>
      <tbody>
        <% @sub_reddit.all_related_subreddit_relations.reverse.each do |related_sub_reddit| %>
          <tr>
    <% if @sub_reddit.id != related_sub_reddit.sub_reddit_relation.id %>
            <td><%= link_to related_sub_reddit.sub_reddit_relation.name, related_sub_reddit.sub_reddit_relation %></td>
    <% end %>
    <% if @sub_reddit.id == related_sub_reddit.sub_reddit_relation.id %>
            <td><%= link_to related_sub_reddit.sub_reddit , related_sub_reddit.sub_reddit %></td>
    <% end %>
            <td>
              <div class="progress">
                <div class="progress-bar" role="progressbar" data-transitiongoal="<%= related_sub_reddit.weight*100 %>"></div>
              </div>
            </td>
            <td><%= link_to 'Edit', edit_related_sub_reddit_path(related_sub_reddit) %></td>
            <td><%= link_to 'Delete', related_sub_reddit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    <% end %>
  </table>

  <%= link_to 'Edit', edit_sub_reddit_path(@sub_reddit) %> |
  <%= link_to 'Back', sub_reddits_path %>
</div>

<script type="text/javascript">
     // // When DOM is ready...
     // $(document).ready(function() {
     //   /*!
     //    * Create an array of word objects, each representing a word in the cloud
     //    */
     //   var word_array =
     //    <%= raw @bag_of_words_word_list.to_json %>;

     //   // Then select the container element and call the jQCloud method, passing the array of words as the first argument.
     //   $("#example").jQCloud(word_array);
     // });
</script>